server:
  port: 10000

spring:
  application:
    name: secolab

  profiles:
    include: oauth

  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:mysql://59.6.55.253:3306/secolab?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true #
    username: openeg
    password: Openeg2020!
    driver: com.mysql.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 2000MB
      max-request-size: 2150MB

mybatis:
  type-aliases-package: com.openeg.sctsusers.entity
  mapper-locations: mapper/**/*.xml

login:
  url:
    path: /users/login
  front-page: http://127.0.0.1/student

token:
  expiration_time: 86400000
  secret: scts_secret

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

access:
  header:
    name: Access-Control-Allow-Origin

##
ip:
  addr: http://127.0.0.1

front:
  host: http://127.0.0.1:3000

save:
  pdf:
    path: /Users/dowonlee/Desktop/Work/secolab-backend/openeg/pdf/
    db-path: /pdf/
    file: file:///Users/dowonlee/Desktop/Work/secolab-backend/openeg/pdf
  video:
    path: /Users/dowonlee/Desktop/Work/secolab-backend/openeg/video/
    db-path : /video/
    file: file:///Users/dowonlee/Desktop/Work/secolab-backend/openeg/video
  code:
    path: /Users/dowonlee/Desktop/Work/secolab-backend/openeg/code/

compile:
  path: /Users/dowonlee/Desktop/Work/secolab-backend/openeg/code/compile/
