server:
  port: 10000

spring:
  application:
    name: secolab

  profiles:
    include: oauth

  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/secolab?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
    username: openeg
    password: Openeg2016!
    driver: com.mysql.jdbc.Driver


  servlet:
    multipart:
      enabled: true
      max-file-size: 2000MB
      max-request-size: 2150MB

mybatis:
  type-aliases-package: com.openeg.sctsusers.entity
  mapper-locations: mapper/**/*.xml

login:
  url:
    path: /users/login

token:
  expiration_time: 86400000
  secret: scts_secret

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

access:
  header:
    name: Access-Control-Allow-Origin

##
# 고정 아이피 주소
ip:
  addr: http://59.6.55.253

# front 포트
front:
  host: http://59.6.55.253:5000

save:
  # pdf 파일 저장 경로
  pdf:
    path: /home/openeg/pdf/
    db-path: /pdf/
    file: file://home/openeg/pdf
  # video 파일 저장 경로
  video:
    path: /home/openeg/video/
    db-path : /video/
    file: file://home/openeg/video
  # 보안약점 코드 파일 저장 경로
  code:
    path: /home/openeg/code/

# 컴파일 파일 저장 경로
compile:
  path: /home/openeg/code/compile/
